*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Aug 30 15:24:08 2021] ***
compiled with version: 9.3.0 on 11 March 2021 00:46:13
os: Linux-4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020
nodename: cdh65.cdh.com
machine: x86_64
clock source: unix
detected number of CPU cores: 48
current working directory: /opt/datamall
writing pidfile to /opt/datamall/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /opt/datamall
your processes number limit is 514486
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:7778 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
PEP 405 virtualenv detected: /root/.virtualenvs/datamall-venv
Set PythonHome to /root/.virtualenvs/datamall-venv
Python main interpreter initialized at 0x56218fb7ee00
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "datamall/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/root/.virtualenvs/datamall-venv/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/root/.virtualenvs/datamall-venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.virtualenvs/datamall-venv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/root/.virtualenvs/datamall-venv/lib/python3.8/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'corsheaders'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2516856)
spawned uWSGI worker 1 (pid: 2516858, cores: 2)
spawned uWSGI worker 2 (pid: 2516859, cores: 2)
spawned uWSGI worker 3 (pid: 2516860, cores: 2)
spawned uWSGI worker 4 (pid: 2516862, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/1] 192.168.2.136 () {38 vars in 576 bytes} [Mon Aug 30 07:24:32 2021] GET /datamall/download/?_id=6128aae1179bd9e90aacbdf5 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/2] 192.168.2.136 () {38 vars in 576 bytes} [Mon Aug 30 07:29:28 2021] GET /datamall/download/?_id=6128aae1179bd9e90aacbdf5 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/3] 192.168.2.136 () {38 vars in 576 bytes} [Mon Aug 30 11:05:21 2021] GET /datamall/download/?_id=6128aae1179bd9e90aacbdf5 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2516860|app: -1|req: -1/4] 192.168.2.136 () {38 vars in 576 bytes} [Tue Aug 31 00:36:48 2021] GET /datamall/download/?_id=6128aae1179bd9e90aacbdf5 => generated 21 bytes in 24 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2516860|app: -1|req: -1/5] 192.168.2.136 () {40 vars in 637 bytes} [Tue Aug 31 00:36:58 2021] GET /datamall/download/?_id=6128aae1179bd9e90aacbdf5 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/6] 192.168.2.136 () {38 vars in 576 bytes} [Tue Aug 31 00:37:00 2021] GET /datamall/download/?_id=6128aae1179bd9e90aacbdf5 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/7] 192.168.2.136 () {38 vars in 517 bytes} [Tue Aug 31 00:37:06 2021] GET /datamall/datatype => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2516860|app: -1|req: -1/8] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 00:37:08 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/9] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 00:37:21 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/10] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 00:55:59 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/11] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 00:56:02 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/12] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 00:56:02 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/13] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 00:56:03 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/14] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 00:56:03 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/15] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 00:56:04 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/16] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 00:56:04 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/17] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 00:57:59 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/18] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 00:58:02 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/19] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 01:18:10 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/20] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 01:18:11 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/21] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 01:18:13 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/22] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 01:18:13 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/23] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 01:19:56 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/24] 192.168.2.136 () {42 vars in 1026 bytes} [Tue Aug 31 01:20:08 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/25] 192.168.2.136 () {44 vars in 1057 bytes} [Tue Aug 31 01:20:09 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 2516862|app: -1|req: -1/26] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 01:21:25 2021] GET /datamall/datatype/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Aug 31 09:24:03 2021] ***
compiled with version: 9.3.0 on 11 March 2021 00:46:13
os: Linux-4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020
nodename: cdh65.cdh.com
machine: x86_64
clock source: unix
detected number of CPU cores: 48
current working directory: /opt/datamall
writing pidfile to /opt/datamall/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /opt/datamall
your processes number limit is 514486
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:7778 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
PEP 405 virtualenv detected: /root/.virtualenvs/datamall-venv
Set PythonHome to /root/.virtualenvs/datamall-venv
Python main interpreter initialized at 0x557f167d6ac0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x557f167d6ac0 pid: 3351742 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3351742)
spawned uWSGI worker 1 (pid: 3351750, cores: 2)
spawned uWSGI worker 2 (pid: 3351751, cores: 2)
spawned uWSGI worker 3 (pid: 3351753, cores: 2)
spawned uWSGI worker 4 (pid: 3351755, cores: 2)
[pid: 3351750|app: 0|req: 1/1] 192.168.2.136 () {38 vars in 519 bytes} [Tue Aug 31 01:24:06 2021] GET /datamall/datatype/ => generated 7754 bytes in 479 msecs (HTTP/1.1 200) 6 headers in 173 bytes (1 switches on core 0)
